crud_rails/store/config/routes.rb
Rails.application.routes.draw do
  #resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/products', to: 'products#index'
  get '/products/new', to: 'products#new'
  post '/products', to: 'products#create'
  get '/product/:id', to: 'products#show', as: 'product'
  get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
  patch '/product/:id', to: 'products#update'
  put '/product/:id', to: 'products#update'
  delete '/product/:id', to: 'products#delete'
end

crud_rails/store/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crud_rails/store/app/models/product.rb
class Product < ApplicationRecord
end

crud_rails/store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

crud_rails/store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def new
    @product = Product.new
  end
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def  update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end
  def delete
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

crud_rails/store/app/helpers/application_helper.rb
module ApplicationHelper
end

crud_rails/store/app/helpers/products_helper.rb
module ProductsHelper
end

crud_rails/store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

crud_rails/store/app/views/products/edit.html.erb
<!DOCTYPE html>
<html>
<head>
    <link href="styles.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<h1>EDIT PRODUCT</h1>
<%= form_for @product do |f| %>
<form>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div

  <div>
    <%= f.submit value="Editar"%>
  </div>

  <% end %>
</form>
</body>
</html>

crud_rails/store/app/views/products/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <link href="styles.css" rel="stylesheet" type="text/css"/>
</head>

<body>

  <h1>BICYCLE</h1>

<div id="main-container">
  
  <table>
    <tr>
      <thead>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Action</th>
      </thead>
    </tr>
      <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td>
        <%= link_to "Update", edit_product_path(product)%>
        <%= link_to "Delete", product, method: :delete, data: { confirm: "Deseas eliminar?"} %>
      </td>
    </tr>
      <% end %>
  </table>

</div>
</body>
</html>

crud_rails/store/app/views/products/new.html.erb
<!DOCTYPE html>
<html>
<head>
    <link href="styles.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<h1>CREATE PRODUCT</h1>
  <%= form_for @product do |f| %>

<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :description %>
  <%= f.text_area :description%>
</div>

<div>
  <%= f.label :price %>
  <%= f.number_field :price %>
</div

<div>
  <%= f.submit value="Create"%>
</div>

<% end %>
</body>
</html>